// Hand-written type entry point (./types/ is generated by `npm run types`).
// Primary exports describe the server surface; ClientAgent names the browser
// implementation available from Meteor's client entry.

export * from './types/server/index';

// The `<agent-chat>` element. Client-only.
export { defineAgentChat } from './types/client/element';

// Browser-side `Agent` under an unambiguous type name. At client runtime this
// alias and `Agent` reference the same browser implementation.
export { Agent as ClientAgent } from './types/client/agent';
