// Hand-written type entry point (./types/ is generated by `npm run types`).
// Default export is the server Agent; ClientAgent is the browser surface.

export * from './types/server/index';

// The `<agent-chat>` element. Client-only.
export { defineAgentChat } from './types/client/element';

// Browser-side `Agent` under its own name. Same class at run time; the alias
// lets both surfaces be imported from one module id.
export { Agent as ClientAgent } from './types/client/agent';
